name: muslim_ku
description: Flutter UI prototype for a Muslim companion app with Adzan and Al-Qur'an flows.
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  cloud_firestore: ^6.3.0
  firebase_auth: ^6.4.0
  firebase_core: ^4.6.0
  flutter:
    sdk: flutter
  flutter_compass: ^0.8.1
  flutter_local_notifications: ^21.0.0
  flutter_secure_storage: ^10.0.0
  flutter_timezone: ^5.0.2
  geolocator: ^14.0.2
  google_sign_in: ^7.2.0
  http: ^1.6.0
  just_audio: ^0.10.5
  just_audio_background: ^0.0.1-beta.17
  local_auth: ^2.3.0
  path_provider: ^2.1.5
  share_plus: ^11.1.0
  speech_to_text: ^7.3.0
  shared_preferences: ^2.5.5
  timezone: ^0.11.0
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

dependency_overrides:
  path_provider_foundation: 2.5.1

flutter:
  uses-material-design: true
  assets:
    - assets/audio/adhan/
    - assets/Logo/
